### PR TITLE
Implemented Issue 715's function

### PR DESCRIPTION
**Pull request by wy193777**
- status bar will show file change status
- fix a bug all git directory treated as dirty

The implementation of issue #715.

### CODE REVIEW

**Comment by drew-gross** [comment]
Awesome, can you include some screenshots too show what it looks like?

**Comment by wy193777** [comment]
screenshot from 2016-10-23 21-57-25

Staged file changes will be shown in green and unstaged will be shown in red. 
Numbers after '+', '~', '-' mean added, changed and deleted files. 

Just pushed a new commit fixed a bug that unstaged change will be counted as staged.

**Comment by drew-gross** [comment]
Looks pretty good. How would you feel about hiding the ones the are zero? I want to avoid the status bar getting too cluttered.

**Comment by wy193777** [comment]
Those numbers will not show if the repository is clean or not a git repository. 

 Yes, I think that's a good idea. I will try to finish this on this week.

**Comment by wy193777** [comment]
Just updated. It will not show 0s now.

**Comment by drew-gross** [comment]
Awesome, thanks. I removed a `console.log` for you and I will merge when tests pass. BTW we have some git related utilities here: https://github.com/shockone/black-screen/blob/master/src/utils/Git.ts that you may find useful in the future. I kinda like your API better though, maybe we should adopt that one throughout the codebase.

**Comment by dmccaffery** [comment]
I was looking into this too! You 'da man, @wy193777

**Comment by dmccaffery** [comment]
... or woman, whichever the case may be... either way, I <3 you!

**Comment by dmccaffery** [comment]
screen shot 2016-10-31 at 1 11 23 am

The only thing I don't like is the mapping between the local branch and the remote branch... that definitely makes it seem cluttered.

**Comment by drew-gross** [comment]
Yeah, I know. It is somewhat useful, but also very cluttered. Maybe we can have that show when you hover your mouse, and when you change branches, but otherwise slide away.

**Comment by wy193777** [comment]
The status on bottom is a little bit verbose after we have file change number.

**Comment by dmccaffery** [comment]
@drew-gross @wy193777 Don't get me wrong; I LOVE this feature, which is why I opened #715 to begin with... I like the simple idea of clicking on the area to "show/hide" additional detail... maybe a three click rotation as follows:

1) branch name only (like it was before)
2) @wy193777 changes with simple branch (no remote map)
3) full detail like it is now

Just keep clicking to rotate through and persist the state

**Comment by drew-gross** [comment]
That sounds like a pretty solid plan. It's kinda like a setting, but also kinda like a persistent UI feature.

**Comment by wy193777** [comment]
Maybe create a new issue about this?

**Comment by drew-gross** [comment]
Good idea. Opened in #862

**Pull request merged**
