### PR TITLE
Add fixPath() to Main.ts, allows correct $PATH on OSX

### LINKED ISSUE #50: The packaged version doesn't read PATH
Extracting @alebcay's comment as a separate issue.

I'm also getting some other weird stuff with `ls` coloring and formatting. This is what I get when I run it through `gulp` - everything works the way it should:

q4ysyk9

but then, when I do `npm run package` and run it from the standalone app bundle, I get this:

af2jiml

It seems that the `gulp` version is reading my path - `which ls` returns my `ls` that I installed from MacPorts. However, the standalone doesn't seem to do that, and is instead using `/bin/ls`. Even so, I still can't figure out why it's only outputting the first line out output with `/bin/ls` (it only shows "Applications", nothing else).

### PR DESCRIPTION
**Pull request by moollaza**
Fixes #50 

I tested this locally and it seems to work. 

I've never used TypeScript before, so I hope this is the correct approach. Please let me know if it isn't!

### CODE REVIEW

**Comment by jdsimcoe** [comment]
@moollaza I built your files and when I try to run `atom .` it gives me this error:

```
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
```

**Comment by cpdean** [comment]
@jdsimcoe are you running `atom .` from within a terminal inside tmux?

**Comment by moollaza** [comment]
@jdsimcoe I tested with `npm start` vs `npm run package` -- the latter, compiled version had the same `$PATH` as the former.

When I run `atom .` nothing happens on the current master branch of black-screen for me...

**Comment by jdsimcoe** [comment]
@cpdean No I'm running `atom .` from within `black-screen`.

**Comment by moollaza** [comment]
@jdsimcoe I'm able to replicate now. It looks like this is an Atom specific bug: https://github.com/atom/atom/issues/3093 -- I see you commented over there :+1: 

Other programs seem to work fine, for example `subl .`

**Comment by shockone** [comment]
Thank you, @moollaza.

**Comment by moollaza** [comment]
@shockone no problem! Thanks for merging :smiley:

**Pull request merged**
