### PR TITLE
Allow cursor to be moved

### PR DESCRIPTION
**Pull request by bmats**
I’m unable to move the cursor away from the end of the line. This issue was reported in #141, but it looks like it was only partially resolved in that ticket.

Changes:
- Move the cursor left and right when the arrow keys are pressed

EDIT: Oops, this PR broke the cursor being positioned by setting the state. I'll work on fixing this.
EDIT 2: Should be fixed now. I updated the changes list above.

### CODE REVIEW

**Comment by iiegor** [comment]
@bmats I created a PR in your branch to fix a minimal issue.

> When we press the right arrow key we can't move the caret to the last char of the right.

**Comment by bmats** [comment]
Thank you @iiegor, merged.

**Comment by shockone** [comment]
Hey, @bmats. Thank you for the fix. However, with this approach we'd need to manually handle all the other movements  as well, for example `⌘+ ←`, which could be handled by Chrome. Perhaps, we should think of a different way. Maybe reposition the caret only  if the buffer content was changed.

**Comment by shockone** [comment]
Fixed.

**Pull request closed without merging**
