### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by sbdchd**
Modified the README a bit to make the installation of Black Screen a bit more clear.

### CODE REVIEW

**Comment by G07cha** [comment]
Also should be added `cd black-screen` after cloning repo

**Comment by sbdchd** [comment]
`cd black-screen` has been added

**Comment by G07cha** [comment]
They are splited so it's looks like 
```bash
cd black-screen
```

```bash
npm run install-all
```
I propose to join two strings
```bash
cd black-screen
npm run install-all
```

**Comment by G07cha** [comment]
:+1:

**Comment by shockone** [comment]
@sbdchd, @G07cha, thank you.

**Pull request merged**
