### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zedtux**
Add installation of Gulp.js

### CODE REVIEW

**Comment by G07cha** [comment]
Gulp exists in devDependencies, so better just move gulp to 'dependencies' object

**Comment by zedtux** [comment]
Thank you @G07cha. Should I move all the `gulp-*` thing or just `"gulp": "3.9.0",` ?

**Comment by shockone** [comment]
@G07cha I'm not sure what's the point of moving it into dependencies. Could you elaborate, please?

**Comment by G07cha** [comment]
Yep, I've just noticed that for production build we don't need gulp at all, so this pull request useless for regular users, but anyway, need to make sure that gulp tasks don't creates files nessesary for electron-package.

**Comment by shockone** [comment]
That's true, but I think the initial issue was that building the terminal is invoked by the `gulp` command, which is not necessarily in the path. As an idea, we can create an `npm` script to start `gulp`. This way it will surely appear in the path.

**Comment by G07cha** [comment]
Hence I think we can close this request and for feature need to create .app build for production and guide in README mark as build for development

**Comment by shockone** [comment]
@zedtux, now you can start the build with `npm start` instead of `gulp`. 

@G07cha, I'll create an issue about the build.

**Comment by zedtux** [comment]
Thank you @shockone for this. I'll give it a try.

**Pull request closed without merging**
