### PR TITLE
Fixes Multi-line Input | issue #112

### PR DESCRIPTION
**Pull request by egladman**
##### this addresses issue #112 HOWEVER this also introduces two minor issues
- the cursor is hidden behind the class: prompt-decoration. Once text is inputted  the cursor becomes visible. 
- the class: autocomplete becomes hidden once it exceeds the viewport

### CODE REVIEW

**Comment by shockone** [comment]
Hey, @egladman. Sorry for a long delay. I'm afraid I have little time now, but I'll test it as soon as possible.

**Comment by egladman** [comment]
@shockone thanks for the update. I will try to address the two minor issues that i unintenially introduced.

**Comment by shockone** [comment]
@egladman, how do you even make a multi line prompt?

**Comment by egladman** [comment]
@shockone short answer: type gibberish. Currently if an excessively long string(without spaces) is entered the line is not wrapped and the overflow is hidden.  I think the overflow should be horizontally scrollable. If you share your thoughts on the matter I can revise my commit.

**Comment by shockone** [comment]
@egladman, I did that in your branch, and it is still not wrapped.

**Comment by pixeldesu** [comment]
If you want to wrap long lines with CSS you should probably attempt using `word-break: break-all;` for the  input.

**Comment by shockone** [comment]
Fixed with CSS Grid Layout.

**Pull request closed without merging**
